version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    command: sh -c "yarn run start:dev"
    ports:
      - 8080:8080
    volumes:
      - ./Nestjs/api:/usr/src/api

  db:
    image: postgres:14
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: postgres
    volumes:
      - ./db:/var/lib/postgresql/data